version: "3"

services:
  app:
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - ".env"
    links:
      - "db:${DB_HOST}"
    volumes:
      - "./migrations/versions:/kaizen/migrations/versions"
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_NAME}"
    env_file:
      - ".env"
    volumes:
      - "./postgres_data:/var/lib/postgresql/data"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8000:8080"
